services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      DATABASE_CLIENT: mongodb
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    env_file:
      - path: ./.env
        required: true
    volumes:
      - ../:/workspace
      # Mount the SSH keys from the host to the container for git access
      - ~/.ssh:/root/.ssh
      # Mount the setup.sh script to the container
      - ./setup.sh:/root/setup.sh
    ports:
      - 3000:3000
    networks:
      - default
    command: ["sleep", "infinity"]

  database:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - default

volumes:
  mongo-data:

networks:
  default:
    name: devcontainer
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: devcontainer
